config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "forecasts#index"
  resources :forecasts, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
# frozen_string_literal: true

class ForecastsController < ApplicationController
  def index
    @location = ""
    @forecast = nil
    @error_messages = nil

    if params[:location].present?
      forecast = Weather::Forecast.get_forecast(params[:location])
      if forecast[:status] == 404
        @error_messages = forecast[:error]
      else
        @forecast = forecast
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecast_helper.rb
# frozen_string_literal: true

module ForecastHelper
  def display_location(forecast)
    forecast["display_name"] || forecast["address"]
  end

  def formatted_date(day)
    Time.parse(day).strftime("%a, %b %d")
  end

  def current_temperature(forecast)
    "#{forecast["current"]["temperature_2m"]}#{forecast["current_units"]["temperature_2m"]}"
  end

  def forecast_min_temperature(forecast, index)
    "#{forecast["daily"]["temperature_2m_min"][index]}#{forecast["daily_units"]["temperature_2m_min"]}"
  end

  def forecast_max_temperature(forecast, index)
    "#{forecast["daily"]["temperature_2m_max"][index]}#{forecast["daily_units"]["temperature_2m_max"]}"
  end
end

app/views/forecasts/_forecast.html.erb
<h2 class="mb-0">Forecast For: <%= display_location(forecast) %></h2>

<% if forecast["cached"] == true %>
  <div class="cached-indicator flex content-center ml-0 pl-0 mt-0 mb-4">
    <svg height="20" width="20" xmlns="http://www.w3.org/2000/svg">
      <circle r="5" cx="10" cy="10" stroke-width="3" class="fill-green-700"  />
      <span class="text-sm">Cached</span>
    </svg>
  </div>
<% end %>

<div class="forecast-details bg-white shadow-md rounded px-8 py-4">
  <p>
    <span class="current-temperature text-2xl">Current Temperature: <%= current_temperature(forecast) %></span>
  </p>
  <p>
    <span class="text-2xl">5 Day Forecast</span>
    <div class="flex justify-center divide-x divide-solid">
      <% forecast["daily"]["time"].each_with_index do |day, index| %>
        <%= render partial: "weather_day", locals: {day: day, forecast: forecast, index: index} %>
      <% end %>
    </div>
  </p>
</div>

app/views/forecasts/_weather_day.html.erb
<div class="forecast-day px-4 first:pl-0 last:pr-0">
  <div class="date">
    <%= formatted_date(day) %>
  </div>
  <div class="temperature">
    <div class="temperature-min">
      <b>L</b> <%= forecast_min_temperature(forecast, index) %>
    </div>
    <div class="temperature-max">
      <b>H</b> <%= forecast_max_temperature(forecast, index) %>
    </div>
  </div>
</div>

app/views/forecasts/index.html.erb
<h1>Weather Forecast</h1>

Enter a location to get the current weather forecast.

<%= form_with url: forecasts_path, method: :get, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 my-4" do |f| %>
  <div class="mb-4">
    <label class="block text-gray-700 text-sm font-bold mb-2" for="location">
      Address or Zipcode
    </label>
    <%= f.text_field :location, value: params[:location], class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div>
    <%= f.submit "Search", data: { turbo_frame: "display_forecast" }, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

<%= turbo_frame_tag 'display_forecast' do %>
  <% if @error_message %>
    <div role="alert" class="bg-red-500 rounded text-white px-4 py-2">
      <%= @error_message %>
    </div>
  <% elsif @forecast %>
    <%= render partial: "forecast", locals: { forecast: @forecast } %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apple</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <main class="container mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>